[build]
  base = "frontend"
  publish = "build"
  command = "CI= npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18" 